name: statping-ng
version-script: cat version.txt
version: "stable"
summary: Statping-ng Server Monitoring with Status Page
description: >
  An easy to use Status Page for your websites and applications.
  Statping will automatically fetch the application and render a beautiful
  status page with tons of features for you to build an even better status page.
  This Status Page generator allows you to use MySQL, Postgres, or SQLite
  on multiple operating systems.
base: base
type: app
confinement: strict
grade: stable
issues: https://github.com/statping-ng/statping-ng/issues

architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64
  - build-on: i386

apps:
  statping:
    command: statping
    plugs:
      - home
      - network
      - network-bind

parts:
  statping:
    source: .
    plugin: nil
    override-build: |
      apt-get update
      apt-get install -y curl tar
      curl -o- -L https://raw.githubusercontent.com/statping-ng/statping-ng/stable/install.sh | bash
      mv /usr/local/bin/statping ./
